### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by ghost** [fleu42/docker-cartodb#6]
I have a number of errors in the installation:

```
./scripts/check-node-canvas.sh: 3: ./scripts/check-node-canvas.sh: [[: not found
```

---

```
Package pangocairo was not found in the pkg-config search path.
Perhaps you should add the directory containing `pangocairo.pc'
to the PKG_CONFIG_PATH environment variable
No package 'pangocairo' found
gyp: Call to 'pkg-config pangocairo --libs' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Linux 3.13.0-46-generic
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Windshaft-cartodb/node_modules/windshaft/node_modules/canvas
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 
```

---

```
npm ERR! canvas@1.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@1.2.1 install script.
npm ERR! This is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.13.0-46-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /Windshaft-cartodb
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

**Comment by stefanavesand** [comment]
I fixed the last issue by adding libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev to the list of packages installed by apt-get in the Dockerfile.

Now I came much further, but it fails on the cartodb:db:setup rake task:
*\* Execute cartodb:db:setup
rake aborted!
{:password=>["is not present", "is not confirmed"]}
/cartodb/lib/tasks/setup.rake:38:in `block (3 levels) in <top (required)>'
/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/rake/task.rb:205:in`call'
/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/rake/task.rb:205:in `block in execute'
/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/rake/task.rb:200:in`each'
/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/rake/task.rb:200:in `execute'
/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/rake/task.rb:158:in`block in invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/rake/task.rb:151:in`invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/rake/task.rb:144:in `invoke'
/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/rake/application.rb:116:in`invoke_task'
/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/rake/application.rb:94:in `block (2 levels) in top_level'
/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/rake/application.rb:94:in`each'
/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/rake/application.rb:94:in `block in top_level'
/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/rake/application.rb:133:in`standard_exception_handling'
/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/rake/application.rb:88:in `top_level'
/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/rake/application.rb:66:in`block in run'
/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/rake/application.rb:133:in `standard_exception_handling'
/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/rake/application.rb:63:in`run'
/usr/local/rvm/rubies/ruby-1.9.3-p547/bin/rake:32:in `<main>'
Tasks: TOP => cartodb:db:setup
2015/03/06 10:57:30 The command [/bin/sh -c service postgresql start && service redis-server start && bash -l -c "cd /cartodb && bash script/create_dev_user" && service postgresql stop && service redis-server stop] returned a non-zero code: 1

**Comment by jbuonagurio** [comment]
@stefanavesand I corrected this issue by updating the user environment variables in [create_dev_user](https://github.com/fleu42/docker-cartodb/create_dev_user#L3-L6). I'm not sure why it didn't accept the defaults.

I also had to update the cartodb-postgresql version in the Dockerfile to 1.7.3 (current) as referenced in fleu42/docker-cartodb@4a89fba2850d7b9f13b3f1b91d7b4d8de830e8d4 to correct an `extension "cartodb" has no update path` error.

Finally, successfully built.

**Comment by stefanavesand** [comment]
Are your maps persistenly stored if you restart the Docker container or do we need to modify it to use the data container pattern?

**Comment by jbuonagurio** [comment]
No they are not persistent - it will need to be modified to use a data container as you suggest. I'll hopefully get around to that this week.

[jbuonagurio/docker-cartodb](https://github.com/jbuonagurio/docker-cartodb) (my fork) now contains a working configuration.

**Comment by trinityXmontoya** [comment]
@jbuonagurio installing your fork errored out : 
```
** Invoke cartodb:db:setup (first_time)
** Invoke db:create (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
Missing basemaps configuration, there should be at least one basemap
/cartodb/config/initializers/01_app_config.rb:47:in `config'
/cartodb/config/initializers/03_mailer.rb:1:in `<top (required)>'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/activesupport-3.2.2/lib/active_support/dependencies.rb:245:in `load'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/activesupport-3.2.2/lib/active_support/dependencies.rb:245:in `block in load'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/activesupport-3.2.2/lib/active_support/dependencies.rb:236:in `load_dependency'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/activesupport-3.2.2/lib/active_support/dependencies.rb:245:in `load'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/railties-3.2.2/lib/rails/engine.rb:588:in `block (2 levels) in <class:Engine>'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/railties-3.2.2/lib/rails/engine.rb:587:in `each'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/railties-3.2.2/lib/rails/engine.rb:587:in `block in <class:Engine>'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/railties-3.2.2/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/railties-3.2.2/lib/rails/initializable.rb:30:in `run'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/railties-3.2.2/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/railties-3.2.2/lib/rails/initializable.rb:54:in `each'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/railties-3.2.2/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/railties-3.2.2/lib/rails/application.rb:136:in `initialize!'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/railties-3.2.2/lib/rails/railtie/configurable.rb:30:in `method_missing'
/cartodb/config/environment.rb:5:in `<top (required)>'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/backports-3.6.4/lib/backports/std_lib.rb:9:in `require'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/backports-3.6.4/lib/backports/std_lib.rb:9:in `require_with_backports'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/railties-3.2.2/lib/rails/application.rb:103:in `require_environment!'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/railties-3.2.2/lib/rails/application.rb:292:in `block (2 levels) in initialize_tasks'
/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/rake/task.rb:205:in `call'
/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/rake/task.rb:205:in `block in execute'
/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/rake/task.rb:200:in `each'
/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/rake/task.rb:200:in `execute'
/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/rake/task.rb:158:in `block in invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/rake/task.rb:151:in `invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/rake/task.rb:176:in `block in invoke_prerequisites'
/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/rake/task.rb:174:in `each'
/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/rake/task.rb:174:in `invoke_prerequisites'
/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/rake/task.rb:157:in `block in invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/rake/task.rb:151:in `invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/rake/task.rb:176:in `block in invoke_prerequisites'
/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/rake/task.rb:174:in `each'
/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/rake/task.rb:174:in `invoke_prerequisites'
/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/rake/task.rb:157:in `block in invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/rake/task.rb:151:in `invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/rake/task.rb:144:in `invoke'
/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/rake/application.rb:116:in `invoke_task'
/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/rake/application.rb:94:in `block (2 levels) in top_level'
/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/rake/application.rb:94:in `each'
/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/rake/application.rb:94:in `block in top_level'
/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/rake/application.rb:133:in `standard_exception_handling'
/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/rake/application.rb:88:in `top_level'
/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/rake/application.rb:66:in `block in run'
/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/rake/application.rb:133:in `standard_exception_handling'
/usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/rake/application.rb:63:in `run'
/usr/local/rvm/rubies/ruby-1.9.3-p547/bin/rake:32:in `<main>'
Tasks: TOP => cartodb:db:setup => db:create => environment
```

(issues are not available to open on the fork)
